import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {root,createContext,extractCourse} from './extract-course.mjs';
const out=path.join(root,'desktop-app/src/content');fs.mkdirSync(path.join(out,'courses'),{recursive:true});fs.mkdirSync(path.join(out,'images'),{recursive:true});
const h=createContext();h.run('courses-db.js');const loader=fs.readFileSync(path.join(root,'tih-course-loader.js'),'utf8');const ids=[...new Set([...Object.keys(h.context.COURSES_DB),...[...loader.match(/var CURRICULUM = \{([\s\S]*?)\};/)[1].matchAll(/"([^"]+)":/g)].map(x=>x[1])])];
const priority=['computer-literacy','project-mgmt','accounting-bookkeeping','webdev','design','entrepreneurship','english-success','ielts','toefl','cybersecurity','quickbooks'];const files=new Set();
const courses=ids.map(id=>{const c=extractCourse(id);c.sourceFiles.forEach(f=>files.add(f));const lessons=c.modules.flatMap(m=>m.lessons);let image='';if(c.image&&!/^https?:/.test(c.image)){const file=path.resolve(root,c.image);if(file.startsWith(root+path.sep)&&fs.existsSync(file)){image='content/images/'+id+path.extname(file);fs.copyFileSync(file,path.join(root,'desktop-app/src',image));}}
if(['computer-literacy','ielts'].includes(id)){
for(const l of lessons){if(l.kind!=='quiz'&&!l.html)throw Error('Missing '+c.title+' material: '+l.title);if(l.kind==='quiz'&&!l.questions.length)throw Error('Missing quiz: '+l.title);l.moduleTitle=c.modules[l.module-1].title;l.videoId=/^[A-Za-z0-9_-]{11}$/.test(l.videoId)?l.videoId:null;}
fs.writeFileSync(path.join(out,'courses/'+id+'.json'),JSON.stringify({...c,full:true,courseId:id,courseTitle:c.title,lessons}));
if(id==='computer-literacy'){const samples=lessons.filter(l=>l.kind==='lesson'&&l.noteSource==='authored').slice(0,3);fs.writeFileSync(path.join(out,'sample.json'),JSON.stringify({courseId:id,courseTitle:c.title,css:c.css,lessons:samples.map(l=>({id:l.id,title:l.title,html:l.html,videoId:/^[A-Za-z0-9_-]{11}$/.test(l.videoId)?l.videoId:null,moduleTitle:c.modules[l.module-1].title}))}));}}
return {id,fullAvailable:['computer-literacy','ielts'].includes(id),counts:{readings:lessons.filter(l=>l.kind==='lesson').length,quizzes:lessons.filter(l=>l.kind==='quiz').length,projects:lessons.filter(l=>l.kind==='project').length,questions:lessons.reduce((n,l)=>n+l.questions.length,0)},title:c.title,description:c.description,category:c.category,level:c.level,outcomes:c.outcomes,about:c.about,requirements:c.requirements,image,lessonCount:lessons.length,videoCount:lessons.filter(l=>l.videoId).length,modules:c.modules.map(m=>({title:m.title,lessons:m.lessons.map(l=>({id:l.id,title:l.title,kind:l.kind}))}))};});
const cfg=createContext();cfg.run('hub-config.js');const config=cfg.context.TIH_SUPABASE_CONFIG;if(!config?.url?.startsWith('https://')||!config?.anonKey?.startsWith('sb_publishable_'))throw Error('Review public account configuration');fs.writeFileSync(path.join(out,'account-config.json'),JSON.stringify(config));files.add('hub-config.js');
courses.sort((a,b)=>(priority.includes(a.id)?priority.indexOf(a.id):100)-(priority.includes(b.id)?priority.indexOf(b.id):100)||a.title.localeCompare(b.title));
fs.copyFileSync(path.join(root,'android-app/app/src/main/res/drawable-nodpi/tih_learning_icon.webp'),path.join(out,'logo.webp'));fs.writeFileSync(path.join(out,'catalog.json'),JSON.stringify(courses));
const manifest={format:1,courses:courses.length,entries:courses.reduce((n,c)=>n+c.lessonCount,0),sourceFiles:Object.fromEntries([...files].sort().map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')]))};fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2));console.log({courses:manifest.courses,entries:manifest.entries,previewLessons:3,fullCourses:2});
