version: 2
updates:
  - package-ecosystem: npm
    directory: /desktop-app
    target-branch: codex/tih-desktop-app
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gradle
    directory: /android-app
    target-branch: codex/tih-native-android
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
