/* TIH complit notes part 2 */
(function(){
if(typeof window==='undefined')return;
window.TIH_TOPIC_NOTES=window.TIH_TOPIC_NOTES||{};
var N=window.TIH_TOPIC_NOTES['computer-literacy']=window.TIH_TOPIC_NOTES['computer-literacy']||{};
function build(m,t,d,b){
return '<div class="study-note"><div class="revision-banner"><strong>Computer Literacy · '+m+'</strong><span>Detailed lesson note</span></div><h3>'+t+'</h3><h4>Definition</h4><p>'+d+'</p>'+b+'<blockquote><strong>Study tip:</strong> Watch the matched video, practise on a computer, then complete the interactive quiz.</blockquote><p><strong>Print:</strong> Browser Print → Save as PDF. <em>'+m+'</em></p></div>';
}
N["Starting and Shutting Down a Computer"]=build("Module 2: Using a Computer for the First Time","Starting and Shutting Down a Computer","Starting powers on the computer so the operating system can load; shutting down closes programs and turns the system off safely.","<ol><li>Connect power; press the power button; wait for Windows to load.</li><li>To shut down: save work, close programs, use Start → Power → Shut down.</li></ol><p>Avoid cutting power suddenly.</p>");
N["Using the Keyboard"]=build("Module 2: Using a Computer for the First Time","Using the Keyboard","The keyboard is the main device for entering text, numbers, and commands.","<ul><li><strong>Enter</strong> — new line or confirm.</li><li><strong>Backspace / Delete</strong> — remove text.</li><li><strong>Shift</strong> — capitals and symbols.</li><li><strong>Ctrl / Alt</strong> — shortcuts (Ctrl+C copy, Ctrl+V paste).</li></ul>");
N["Using a Computer Mouse"]=build("Module 2: Using a Computer for the First Time","Using a Computer Mouse","A mouse controls the on-screen pointer through pointing, clicking, double-clicking, right-clicking, and dragging.","<ul><li><strong>Left-click</strong> — select.</li><li><strong>Double-click</strong> — open.</li><li><strong>Right-click</strong> — context menu.</li><li><strong>Drag</strong> — move items.</li></ul>");
N["Understanding the Desktop"]=build("Module 2: Using a Computer for the First Time","Understanding the Desktop","The desktop is the main Windows workspace after login, showing icons, the taskbar, Start button, and background.","<ul><li><strong>Icons</strong> — shortcuts.</li><li><strong>Taskbar</strong> — open apps.</li><li><strong>Start</strong> — find apps and power options.</li></ul>");
N["Using Windows Icons"]=build("Module 2: Using a Computer for the First Time","Using Windows Icons","Icons are small pictures representing programs, files, folders, or tools.","<p>Double-clicking usually opens the item. Deleting a shortcut does not uninstall the program.</p>");
N["Using the Taskbar"]=build("Module 2: Using a Computer for the First Time","Using the Taskbar","The taskbar is used to open programs, switch windows, search, and view system status.","<ul><li>Launch pinned programs.</li><li>Switch between open windows.</li><li>Check time, Wi-Fi, and sound.</li></ul>");
N["Opening and Closing Programs"]=build("Module 2: Using a Computer for the First Time","Opening and Closing Programs","Opening launches application software; closing exits it properly so work can be saved.","<p>Open from Start, desktop icons, or the taskbar. Close with the X or Alt+F4. Always save before closing.</p>");
N["Using Windows Search"]=build("Module 2: Using a Computer for the First Time","Using Windows Search","Windows Search finds apps, settings, and files by keyword from the taskbar search box.","<ol><li>Click search or press the Windows key.</li><li>Type a program, setting, or file name.</li><li>Select the best result.</li></ol>");
N["What Is an Operating System?"]=build("Module 3: Windows Operating System","What Is an Operating System?","An operating system (OS) is system software that manages hardware and software resources and provides the environment in which programs run.","<p>The OS starts when you turn on the computer. Examples include Windows, macOS, Linux, Android, and iOS. This course focuses on Windows.</p>");
N["Introduction to Windows"]=build("Module 3: Windows Operating System","Introduction to Windows","Microsoft Windows is a widely used operating system with a graphical interface based on windows, icons, menus, and a pointer.","<p>Core elements include the desktop, Start menu, taskbar, File Explorer, and Settings.</p>");
N["Windows Desktop"]=build("Module 3: Windows Operating System","Windows Desktop","The Windows desktop is the primary graphical workspace after login.","<p>Pin frequent apps to the taskbar. Store documents in Documents or organized folders.</p>");
N["Windows Settings"]=build("Module 3: Windows Operating System","Windows Settings","Windows Settings is the control centre for configuring accounts, display, sound, network, privacy, apps, and updates.","<p>Open with Start → Settings or Windows key + I.</p>");
N["Control Panel"]=build("Module 3: Windows Operating System","Control Panel","Control Panel is a traditional Windows configuration tool; many functions also appear in Settings.","<p>Use it to uninstall programs and access advanced options.</p>");
N["Installing Software"]=build("Module 3: Windows Operating System","Installing Software","Installing software adds a program so it can be opened and used, usually via an official installer.","<ol><li>Obtain software from trusted sources only.</li><li>Run the installer and follow steps.</li><li>Confirm the program opens from Start.</li></ol>");
N["Uninstalling Software"]=build("Module 3: Windows Operating System","Uninstalling Software","Uninstalling removes a program using Windows tools so files are cleaned up properly.","<p>Settings → Apps → Installed apps → Uninstall.</p>");
N["Windows Updates"]=build("Module 3: Windows Operating System","Windows Updates","Windows Updates are official patches that fix security weaknesses, correct errors, and sometimes add features.","<p>Settings → Windows Update → Check for updates. Install when offered and restart if required.</p>");
N["What Are Files and Folders?"]=build("Module 4: Files and Folders","What Are Files and Folders?","A file is a named collection of stored data; a folder is a container used to group files and other folders.","<p>Every file has a name and type (e.g., .docx, .xlsx, .pdf). File Explorer is the tool for viewing and managing files.</p>");
N["Creating a Folder"]=build("Module 4: Files and Folders","Creating a Folder","Creating a folder makes a new container so related files can be stored under a clear name.","<ol><li>Open File Explorer.</li><li>Right-click → New → Folder.</li><li>Type a meaningful name and press Enter.</li></ol>");
N["Renaming Files and Folders"]=build("Module 4: Files and Folders","Renaming Files and Folders","Renaming changes the name of a file or folder without changing the content inside.","<p>Select the item → F2 (or right-click → Rename). Keep the correct file extension.</p>");
N["Copying and Moving Files"]=build("Module 4: Files and Folders","Copying and Moving Files","Copying creates a duplicate; moving relocates the original without leaving a copy.","<ul><li>Copy: Ctrl+C then Ctrl+V.</li><li>Move: Ctrl+X then Ctrl+V.</li></ul>");
N["Deleting Files and Folders"]=build("Module 4: Files and Folders","Deleting Files and Folders","Deleting usually sends items to the Recycle Bin for possible recovery until the Bin is emptied.","<p>Select → Delete. Be careful with Shift+Delete.</p>");
N["Using Recycle Bin"]=build("Module 4: Files and Folders","Using Recycle Bin","The Recycle Bin holds deleted files so they can be restored if removed by mistake.","<p>Open Recycle Bin → Restore to recover, or Empty Recycle Bin to remove permanently.</p>");
N["Searching for Files"]=build("Module 4: Files and Folders","Searching for Files","File search locates documents by name or content using Windows Search or File Explorer.","<p>Type part of the name in search and open the correct result. Clear naming makes search reliable.</p>");
N["Organizing Your Files"]=build("Module 4: Files and Folders","Organizing Your Files","Organizing files means using a clear folder structure, descriptive names, and ongoing maintenance.","<ul><li>Main folders by purpose: School, Work, Personal.</li><li>Subfolders by subject, client, or year.</li><li>Archive old work rather than deleting everything.</li></ul>");
})();
