/* TIH complit notes part 1 */
(function(){
if(typeof window==='undefined')return;
window.TIH_TOPIC_NOTES=window.TIH_TOPIC_NOTES||{};
var N=window.TIH_TOPIC_NOTES['computer-literacy']=window.TIH_TOPIC_NOTES['computer-literacy']||{};
function build(m,t,d,b){
return '<div class="study-note"><div class="revision-banner"><strong>Computer Literacy · '+m+'</strong><span>Detailed lesson note</span></div><h3>'+t+'</h3><h4>Definition</h4><p>'+d+'</p>'+b+'<blockquote><strong>Study tip:</strong> Watch the matched video, practise on a computer, then complete the interactive quiz for this topic.</blockquote><p><strong>Print:</strong> Browser Print → Save as PDF. <em>'+m+'</em></p></div>';
}
N['__course_intro__']=build('Course Overview','What Is Computer Literacy?','Computer literacy is the ability to use computers and related technology efficiently, confidently, and safely for learning, work, and everyday tasks—including hardware and software understanding, file management, responsible internet use, email, and creating documents, spreadsheets, and presentations.','<p>This Complete Computer Literacy Professional Certificate is a structured beginner-to-competent programme covering Windows, files, internet safety, email, Microsoft Office, Google Workspace, video meetings, maintenance, and workplace digital skills.</p><h4>How to study each lesson</h4><ol><li>Watch the video and follow along on your computer.</li><li>Read this formal note for definitions and key points.</li><li>Practise, then take the short interactive quiz.</li><li>Save printable PDF notes for revision.</li></ol><h4>Outcomes</h4><ul><li>Operate a Windows PC with confidence.</li><li>Organize files and protect data.</li><li>Use internet and email safely and professionally.</li><li>Create Word, Excel, and PowerPoint work.</li><li>Collaborate with Google tools and online meetings.</li><li>Apply digital skills at school and work.</li></ul>');
N["What Is a Computer?"]=build("Module 1: Introduction to Computers","What Is a Computer?","A computer is an electronic device that accepts data (input), processes it according to a program, stores information, and produces useful results (output).","<p>Computer literacy begins with understanding what a computer is designed to do. A computer does not think independently; it follows instructions called <strong>programs</strong> or <strong>software</strong>.</p><h4>Four basic functions</h4><ol><li><strong>Input</strong> — receiving data (typing, clicking, scanning).</li><li><strong>Processing</strong> — transforming data with the CPU.</li><li><strong>Storage</strong> — keeping data in memory or on long-term devices.</li><li><strong>Output</strong> — presenting results on screen, speakers, or paper.</li></ol><p>Computers support education, business, health care, and communication. Literacy means using these tools confidently, safely, and productively.</p>");
N["Types of Computers"]=build("Module 1: Introduction to Computers","Types of Computers","Types of computers classify devices by size, power, purpose, and portability—desktops, laptops, tablets, smartphones, servers, and mainframes.","<ul><li><strong>Desktop</strong> — fixed on a desk; powerful and expandable.</li><li><strong>Laptop</strong> — portable with battery; ideal for students.</li><li><strong>Tablet</strong> — touch-screen for reading and light work.</li><li><strong>Smartphone</strong> — pocket computer for calls, messages, and apps.</li><li><strong>Server</strong> — provides services to many users on a network.</li></ul><p>For full computer literacy, a Windows desktop or laptop is the most practical starting point.</p>");
N["Parts of a Computer"]=build("Module 1: Introduction to Computers","Parts of a Computer","The parts of a computer are the physical units of a working system—typically the system unit, monitor, keyboard, mouse, and optional peripherals such as a printer.","<ul><li><strong>System unit</strong> — motherboard, CPU, memory, storage.</li><li><strong>Monitor</strong> — visual display.</li><li><strong>Keyboard and mouse</strong> — primary input.</li><li><strong>Speakers / printer</strong> — sound and paper output.</li></ul>");
N["Computer Hardware"]=build("Module 1: Introduction to Computers","Computer Hardware","Computer hardware is the tangible physical equipment of a computer—anything you can touch—including the processor, memory, storage, monitor, keyboard, and mouse.","<h4>Categories</h4><ul><li><strong>Processing</strong> — CPU.</li><li><strong>Memory</strong> — RAM and ROM.</li><li><strong>Storage</strong> — HDD, SSD, USB drives.</li><li><strong>Input / Output</strong> — keyboard, mouse, monitor, printer.</li></ul>");
N["Computer Software"]=build("Module 1: Introduction to Computers","Computer Software","Computer software is the set of programs and instructions that tell hardware what to do. Software is intangible but essential for every useful task.","<ul><li><strong>System software</strong> — operating systems (e.g., Windows), drivers, utilities.</li><li><strong>Application software</strong> — Word, Excel, browsers, email.</li></ul>");
N["Hardware vs. Software"]=build("Module 1: Introduction to Computers","Hardware vs. Software","Hardware is the physical equipment of a computer; software is the programs that run on that equipment. Both are required for useful work.","<p><strong>Example:</strong> A printer is hardware; the program that sends a document to it is software.</p>");
N["Input Devices"]=build("Module 1: Introduction to Computers","Input Devices","An input device is hardware used to enter data or commands into a computer—such as a keyboard, mouse, scanner, microphone, or webcam.","<ul><li><strong>Keyboard</strong> — text and commands.</li><li><strong>Mouse / touchpad</strong> — pointing and selection.</li><li><strong>Scanner / microphone / webcam</strong> — paper, sound, and video input.</li></ul>");
N["Output Devices"]=build("Module 1: Introduction to Computers","Output Devices","An output device presents processing results to the user—commonly a monitor, printer, speakers, or projector.","<ul><li><strong>Monitor</strong> — visual display.</li><li><strong>Printer</strong> — paper copies.</li><li><strong>Speakers</strong> — sound.</li></ul>");
N["Storage Devices"]=build("Module 1: Introduction to Computers","Storage Devices","A storage device saves digital data so it remains available after the computer is switched off—hard drives, SSDs, USB flash drives, and cloud storage.","<ul><li><strong>HDD / SSD</strong> — main internal storage.</li><li><strong>USB flash drive</strong> — portable transfer.</li><li><strong>Cloud storage</strong> — Google Drive, OneDrive.</li></ul><p><strong>Rule:</strong> keep more than one copy of important work.</p>");
N["Computer Memory: RAM and ROM"]=build("Module 1: Introduction to Computers","Computer Memory: RAM and ROM","RAM is fast temporary working memory; ROM stores permanent startup instructions.","<h4>RAM</h4><ul><li>Holds open programs and active data.</li><li>Volatile (cleared when power is off).</li></ul><h4>ROM</h4><ul><li>Stores firmware to start the computer.</li><li>Non-volatile.</li></ul>");
})();
