/* TIH complit notes part 4 — Word & Excel */
(function(){
if(typeof window==='undefined')return;
window.TIH_TOPIC_NOTES=window.TIH_TOPIC_NOTES||{};
var N=window.TIH_TOPIC_NOTES['computer-literacy']=window.TIH_TOPIC_NOTES['computer-literacy']||{};
function build(m,t,d,b){
return '<div class="study-note"><div class="revision-banner"><strong>Computer Literacy · '+m+'</strong><span>Detailed lesson note</span></div><h3>'+t+'</h3><h4>Definition</h4><p>'+d+'</p>'+b+'<blockquote><strong>Study tip:</strong> Watch the matched video, practise on a computer, then complete the interactive quiz for this topic.</blockquote><p><strong>Print:</strong> Browser Print → Save as PDF. <em>'+m+'</em></p></div>';
}

N["Introduction to Microsoft Word"]=build("Module 8: Microsoft Word","Introduction to Microsoft Word","Microsoft Word is word-processing application software used to create, edit, format, and print text documents such as letters, reports, and résumés.","<p>Word is a standard workplace tool worldwide. Documents are pages of text you can format and save. Common file types include <strong>.docx</strong> (modern Word) and <strong>.pdf</strong> (for sharing a fixed layout). The Ribbon at the top holds tools under Home, Insert, Layout, and other tabs.</p><h4>Why it matters</h4><p>Professional written communication—school assignments, job applications, official letters—depends on clear, well-formatted documents.</p>");

N["Creating a Word Document"]=build("Module 8: Microsoft Word","Creating a Word Document","Creating a Word document means opening Word and starting a new blank file or template in which you type and save your work.","<ol><li>Open Microsoft Word.</li><li>Choose Blank document (or a template).</li><li>Type your content.</li><li>Save early and often with <strong>Ctrl+S</strong>, using a clear file name in a known folder.</li></ol><p>Saving early protects your work if the program or computer closes unexpectedly.</p>");

N["Typing and Editing Text"]=build("Module 8: Microsoft Word","Typing and Editing Text","Typing enters text at the cursor; editing includes inserting, deleting, selecting, copying, cutting, and pasting text to improve the document.","<ul><li>Click to place the cursor; type to insert text.</li><li>Select text by dragging or double-clicking a word.</li><li><strong>Ctrl+C</strong> copy, <strong>Ctrl+X</strong> cut, <strong>Ctrl+V</strong> paste.</li><li><strong>Ctrl+Z</strong> undoes the last change.</li></ul><p>Edit for clarity: short sentences and clear paragraphs improve professional documents.</p>");

N["Formatting Text"]=build("Module 8: Microsoft Word","Formatting Text","Text formatting changes the appearance of characters and paragraphs—font, size, bold, italic, colour, alignment, and spacing—without changing the words themselves.","<ul><li><strong>Bold / Italic / Underline</strong> — emphasis.</li><li><strong>Font and size</strong> — readability (about 11–12 pt for body text).</li><li><strong>Alignment</strong> — left, centre, right, or justify.</li><li><strong>Line spacing</strong> — space between lines.</li></ul><p>Use formatting consistently. Excess colour and mixed fonts look unprofessional.</p>");

N["Using Styles and Headings"]=build("Module 8: Microsoft Word","Using Styles and Headings","Styles are named sets of formatting. Heading styles structure a document into titled sections and support automatic tables of contents and navigation.","<ul><li>Apply <strong>Heading 1</strong> for main titles.</li><li>Apply <strong>Heading 2</strong> for subsections.</li><li>Use <strong>Normal</strong> for body paragraphs.</li></ul><p>Consistent styles make long documents easier to read, update, and navigate.</p>");

N["Creating Lists"]=build("Module 8: Microsoft Word","Creating Lists","Lists organize items as bullets (unordered) or numbers (ordered), improving clarity for steps, requirements, and inventories.","<ul><li>Use <strong>bullets</strong> for related items without a required sequence.</li><li>Use <strong>numbers</strong> for steps that must follow an order.</li><li>Keep list items parallel in wording.</li></ul>");

N["Inserting Pictures"]=build("Module 8: Microsoft Word","Inserting Pictures","Inserting pictures places images into a document to illustrate ideas, then allows resizing and positioning relative to text.","<ol><li>Insert → Pictures → select the image file.</li><li>Resize using corner handles to avoid distortion.</li><li>Use Wrap Text options so text flows appropriately around the image.</li></ol><p>Use images you have rights to use. Compress large images if the file becomes too big to email.</p>");

N["Creating Tables"]=build("Module 8: Microsoft Word","Creating Tables","A table arranges information in rows and columns for schedules, comparisons, and structured data inside a Word document.","<ol><li>Insert → Table → choose rows and columns.</li><li>Type into cells; use Tab to move between cells.</li><li>Adjust borders and shading for clarity.</li></ol>");

N["Page Layout and Margins"]=build("Module 8: Microsoft Word","Page Layout and Margins","Page layout controls how content sits on the page—margins, orientation (portrait or landscape), size, and breaks.","<ul><li>Layout (or Page Layout) tab → Margins, Orientation, Size.</li><li>Standard margins (about 2.54 cm / 1 inch) are common for formal work.</li><li>Portrait is the default; landscape suits wide tables.</li></ul>");

N["Headers, Footers and Page Numbers"]=build("Module 8: Microsoft Word","Headers, Footers and Page Numbers","Headers and footers are regions at the top and bottom of each page for repeated information such as titles, dates, and page numbers.","<ol><li>Insert → Header or Footer.</li><li>Add text or page numbers.</li><li>Close Header and Footer to return to the body.</li></ol><p>Page numbers help readers navigate multi-page reports and assignments.</p>");

N["Saving a Word Document"]=build("Module 8: Microsoft Word","Saving a Word Document","Saving stores the document on a drive or in the cloud so work is not lost when Word closes or the computer shuts down.","<ul><li><strong>Ctrl+S</strong> for a quick save.</li><li>File → Save As to choose folder, name, and type.</li><li>Save early; save after major changes.</li><li>Keep a backup copy of important files.</li></ul>");

N["Printing and Saving as PDF"]=build("Module 8: Microsoft Word","Printing and Saving as PDF","Printing produces a paper copy; saving as PDF creates a portable fixed-layout file that looks consistent on most devices.","<ul><li>File → Print to select printer and settings.</li><li>File → Save As → PDF (or Export) for electronic submission.</li><li>PDF is preferred when the recipient may not have Word.</li></ul>");

N["Introduction to Microsoft Excel"]=build("Module 9: Microsoft Excel","Introduction to Microsoft Excel","Microsoft Excel is spreadsheet software used to organize data in rows and columns, perform calculations, and create charts for analysis and reporting.","<p>Excel is essential for budgets, registers, grades, inventories, and business records. A file is a <strong>workbook</strong>; sheets inside it are <strong>worksheets</strong>. Data sits in <strong>cells</strong>. Formulas and functions calculate results automatically.</p>");

N["Understanding the Excel Interface"]=build("Module 9: Microsoft Excel","Understanding the Excel Interface","The Excel interface includes the Ribbon, formula bar, grid of cells, sheet tabs, and status bar used to enter and analyse data.","<ul><li><strong>Name box</strong> — shows the selected cell address (e.g., A1).</li><li><strong>Formula bar</strong> — edit cell content and formulas.</li><li><strong>Sheet tabs</strong> — switch between worksheets.</li><li><strong>Ribbon</strong> — Home, Insert, Data, Formulas tabs.</li></ul>");

N["Workbooks and Worksheets"]=build("Module 9: Microsoft Excel","Workbooks and Worksheets","A workbook is an Excel file; a worksheet is a single grid page within that file. One workbook can hold many worksheets for related data.","<ul><li>Rename sheet tabs for clarity (e.g., January, Summary).</li><li>Insert or delete sheets as needed.</li><li>Save the whole workbook to keep all sheets together.</li></ul>");

N["Rows, Columns and Cells"]=build("Module 9: Microsoft Excel","Rows, Columns and Cells","Columns are vertical (labelled A, B, C…); rows are horizontal (1, 2, 3…); a cell is one box identified by column letter and row number (e.g., B3).","<ul><li>Click a cell to select it; type to enter data.</li><li>Use arrow keys or Enter/Tab to move.</li><li>Select ranges (e.g., A1:A10) for formatting or formulas.</li></ul>");

N["Entering Data"]=build("Module 9: Microsoft Excel","Entering Data","Entering data means typing numbers, text, or dates into cells in a structured way so that sorting, filtering, and formulas work correctly.","<ul><li>Put column titles in the first row.</li><li>Keep one type of information per column.</li><li>Avoid empty rows inside a data table when possible.</li><li>Press Enter to confirm a cell entry.</li></ul>");

N["Formatting Cells"]=build("Module 9: Microsoft Excel","Formatting Cells","Cell formatting controls number style, alignment, fonts, borders, and colours so data is readable and professionally presented.","<ul><li>Apply Currency, Percentage, or Date formats where appropriate.</li><li>Bold header rows; adjust column widths.</li><li>Use borders for printed tables.</li><li>Do not overuse bright fill colours.</li></ul>");

N["Basic Excel Formulas"]=build("Module 9: Microsoft Excel","Basic Excel Formulas","A formula is an expression beginning with = that calculates a result from values or cell references, such as =A1+B1.","<ul><li>Always start with <strong>=</strong>.</li><li>Use cell references so results update when data changes.</li><li>Common operators: + − * /.</li><li>Example: <code>=C2-D2</code> for a simple difference.</li></ul>");

N["Excel Functions"]=build("Module 9: Microsoft Excel","Excel Functions","Functions are named calculations built into Excel, such as SUM, AVERAGE, MIN, MAX, and COUNT, written with parentheses.","<ul><li><code>=SUM(A1:A10)</code> adds a range.</li><li><code>=AVERAGE(B2:B20)</code> finds the mean.</li><li><code>=MAX(C2:C50)</code> finds the largest value.</li><li>Use Insert Function if you are unsure of syntax.</li></ul>");

N["Sorting Data"]=build("Module 9: Microsoft Excel","Sorting Data","Sorting arranges rows in order based on one or more columns—alphabetical, numerical, or by date.","<ol><li>Select the data table including headers.</li><li>Data → Sort.</li><li>Choose the column and order (A to Z or smallest to largest).</li></ol><p>Ensure all related columns are selected so rows stay aligned.</p>");

N["Filtering Data"]=build("Module 9: Microsoft Excel","Filtering Data","Filtering temporarily hides rows that do not meet criteria so you can focus on a subset of records.","<ol><li>Select the header row → Data → Filter.</li><li>Use the drop-down arrows on headers to choose values.</li><li>Clear the filter to show all rows again.</li></ol>");

N["Creating Charts"]=build("Module 9: Microsoft Excel","Creating Charts","Charts turn numeric data into visual diagrams—columns, bars, lines, or pies—so patterns are easier to understand.","<ol><li>Select the data including labels.</li><li>Insert → Charts → choose a suitable type.</li><li>Add a clear chart title and axis labels.</li></ol><p>Choose chart types that match the story of the data; avoid effects that distort reading.</p>");

N["Creating a Simple Spreadsheet Project"]=build("Module 9: Microsoft Excel","Creating a Simple Spreadsheet Project","A simple spreadsheet project applies Excel skills end-to-end: plan columns, enter data, format, calculate with formulas, and present results with a chart or summary.","<ol><li>Define the purpose (budget, attendance, inventory).</li><li>Design headers and enter sample or real data.</li><li>Add formulas/functions for totals.</li><li>Format and optionally chart the results.</li><li>Save and back up the workbook.</li></ol>");
})();
