/* TIH Entrepreneurship formal notes — Modules 1–2 */
(function(){
if(typeof window==='undefined')return;
window.TIH_ENT_NOTES_DATA=window.TIH_ENT_NOTES_DATA||[];
var D=window.TIH_ENT_NOTES_DATA;
function a(t,m,d,b){D.push([t,m,d,b]);}

a("Welcome to the Program","Module 1: Course Orientation","The Complete Entrepreneurship & Startup Launch Program is a structured 20-module pathway that takes learners from entrepreneurial mindset and idea generation through to a launched, growing business and a Certificate of Completion.","<p>You will build practical skills in research, business modelling, product, marketing, sales, finance, funding, legal structure, operations, HR, technology, communication, planning, launch, and growth. Every content lesson pairs a video with formal notes and a short practice quiz.</p><h4>Key points</h4><ul><li>Treat the course as applied work on a real (or candidate) business idea.</li><li>Complete action steps and projects; they feed your final plan and pitch.</li><li>Print notes for offline revision and mentor review.</li></ul>");

a("How to Study This Course","Module 1: Course Orientation","Effective study in this programme means watching each video, reading the formal note, applying the idea to your venture, taking one concrete action, and confirming understanding with the practice quiz.","<h4>Recommended routine</h4><ol><li>Watch the matched educational video.</li><li>Read the definition, explanation, and key points.</li><li>Write how the topic applies to your idea.</li><li>Complete the two action steps and the quiz.</li></ol><p>Consistency beats intensity: small weekly progress compounds into a complete business plan and pitch deck.</p>");

a("What is Entrepreneurship?","Module 1: Course Orientation","Entrepreneurship is the process of identifying a business opportunity, mobilising resources, accepting calculated risk, and creating a venture that delivers value to customers—typically with the aim of sustainable revenue and impact.","<p>It is more than “starting a shop.” It includes innovation, problem-solving, customer focus, and the discipline to test assumptions before heavy investment.</p><h4>Key characteristics</h4><ul><li>Opportunity recognition</li><li>Value creation for others</li><li>Resource mobilisation</li><li>Calculated risk-taking</li><li>Learning from feedback and iteration</li></ul>");

a("What is a Startup?","Module 1: Course Orientation","A startup is a temporary organisation designed to search for a repeatable and scalable business model under conditions of extreme uncertainty.","<p>Unlike a traditional small business that often follows a known model, a startup experiments to discover what customers will pay for and how to deliver it profitably at scale.</p><h4>Key points</h4><ul><li>Search mode first; scale only after product–market fit.</li><li>Uncertainty is normal; evidence reduces it.</li><li>Not every small business is a startup—and that is fine.</li></ul>");

a("Entrepreneur vs. Business Owner","Module 1: Course Orientation","An entrepreneur creates and innovates under uncertainty to build new value; a business owner operates and manages an existing or conventional enterprise. Many people are both at different times.","<ul><li><strong>Entrepreneur</strong> — invents or significantly improves offerings, models, or markets.</li><li><strong>Business owner</strong> — owns and runs a venture, which may or may not be highly innovative.</li></ul><p>Both roles require responsibility, customers, and sound management. This course emphasises the entrepreneurial path from idea to growth.</p>");

a("Types of Entrepreneurs","Module 1: Course Orientation","Entrepreneurs can be classified by motivation and model—for example small-and-medium enterprise (SME) founders, innovation-driven founders, social entrepreneurs, and lifestyle entrepreneurs.","<ul><li><strong>SME / local business</strong> — serve a defined local or niche market.</li><li><strong>Innovation-driven</strong> — seek scalable, often technology-enabled growth.</li><li><strong>Social</strong> — prioritise measurable social or environmental impact with a viable model.</li><li><strong>Lifestyle</strong> — design the business around preferred way of living and work.</li></ul><p>Knowing your type helps you choose the right goals, funding path, and metrics.</p>");

a("Startup Success Stories","Module 1: Course Orientation","Startup success stories are documented cases of founders who validated a problem, iterated a solution, found product–market fit, and built a durable organisation—often after early failures and pivots.","<p>Use stories as pattern recognition, not as scripts to copy. Look for: problem intensity, customer evidence, team learning speed, and disciplined use of capital.</p>");

a("Course Roadmap","Module 1: Course Orientation","The course roadmap sequences twenty modules from orientation and mindset through research, modelling, product, go-to-market, finance, legal, operations, and growth, ending with projects and graduation assessments.","<h4>Journey summary</h4><ol><li>Mindset and ideas</li><li>Research and business model</li><li>Product, brand, marketing, sales</li><li>Finance, funding, legal, operations, HR, tech</li><li>Plan, launch, grow</li><li>Projects, exams, certificate</li></ol>");

a("Final Capstone Project","Module 1: Course Orientation","The final capstone integrates your idea, research, business model, plan, financials, and pitch into a coherent founder deliverable assessed at the end of the programme.","<p>Work backward from the capstone: every module should leave an artefact you can drop into the plan or pitch deck.</p>");

a("Developing an Entrepreneurial Mindset","Module 2: Entrepreneurial Mindset","An entrepreneurial mindset is a set of beliefs and behaviours—proactivity, resilience, creativity, calculated risk tolerance, and growth-oriented learning—that drive people to create value and turn ideas into reality.","<h4>Core traits</h4><ul><li>Proactivity and initiative</li><li>Resilience and grit after setbacks</li><li>Creativity and constructive dissatisfaction with the status quo</li><li>Comfort with incomplete information</li><li>Belief that skills improve with effort (growth orientation)</li></ul>");

a("Creativity and Innovation","Module 2: Entrepreneurial Mindset","Creativity is generating useful new ideas; innovation is implementing those ideas so customers experience new or improved value.","<p>Founders need both: many ideas fail without execution, and execution without novelty often competes only on price.</p>");

a("Identifying Opportunities","Module 2: Entrepreneurial Mindset","Opportunity identification is the disciplined search for unmet needs, inefficiencies, or emerging trends where a venture can create and capture value.","<ul><li>Observe friction in daily life and work.</li><li>Listen for complaints and workarounds.</li><li>Track technology, regulation, and demographic shifts.</li></ul>");

a("Solving Real Problems","Module 2: Entrepreneurial Mindset","Solving real problems means focusing on pain that customers already feel and will pay to reduce—not problems that only exist in the founder’s imagination.","<p>Validate intensity and frequency of the problem before building a full solution.</p>");

a("Growth Mindset","Module 2: Entrepreneurial Mindset","A growth mindset is the belief that abilities can be developed through deliberate practice, feedback, and persistence, rather than fixed at birth.","<p>Founders with a growth mindset treat setbacks as data, seek critique, and invest in skill-building instead of defending a fragile ego.</p>");

a("Leadership Skills","Module 2: Entrepreneurial Mindset","Leadership skills for founders include setting direction, communicating clearly, making timely decisions, modelling values, and enabling others to perform.","<p>Early leadership is often personal example and clarity more than hierarchy.</p>");

a("Decision Making","Module 2: Entrepreneurial Mindset","Decision making under uncertainty uses the best available evidence, small experiments, clear criteria, and scheduled review—rather than endless delay or pure guesswork.","<ul><li>Define the decision and deadline.</li><li>List options and risks.</li><li>Run a cheap test where possible.</li><li>Decide, act, review.</li></ul>");

a("Critical Thinking","Module 2: Entrepreneurial Mindset","Critical thinking is the careful evaluation of claims, evidence, and assumptions so founders avoid expensive self-deception.","<p>Ask: What would change my mind? What evidence would falsify this idea?</p>");

a("Time Management","Module 2: Entrepreneurial Mindset","Time management is prioritising high-leverage founder work—customer learning, product, sales, and cash—over low-value busyness.","<p>Protect deep work blocks; batch admin; review priorities weekly.</p>");

a("Personal Productivity","Module 2: Entrepreneurial Mindset","Personal productivity is the reliable system of habits, tools, and environment that lets a founder convert intention into completed outcomes.","<ul><li>One primary goal per day</li><li>Written next actions</li><li>Health and rest as performance infrastructure</li></ul>");
})();
