/* ============================================================
   TIH LEARNING HUB — VIDEO OVERRIDES (module + topic)
   ------------------------------------------------------------
   MODULES[courseId][moduleNumber] = default video for a whole module.
   TOPICS[courseId]['M<n>:Topic Title'] = a specific topic (wins).
   Accepts full YouTube links OR bare 11-char ids. Playlist links are
   ignored. Title match ignores the '3.1 ' numbering, emojis and case.
   ============================================================ */
(function () {
  function vid(u) {
    u = String(u || '').trim();
    if (/^[A-Za-z0-9_-]{11}$/.test(u)) return u;
    var m = u.match(/[?&]v=([A-Za-z0-9_-]{11})/) || u.match(/youtu\.be\/([A-Za-z0-9_-]{11})/) ||
            u.match(/\/embed\/([A-Za-z0-9_-]{11})/) || u.match(/\/shorts\/([A-Za-z0-9_-]{11})/) ||
            u.match(/\/live\/([A-Za-z0-9_-]{11})/);
    return m ? m[1] : '';
  }
  var MODULES = {};
  var TOPICS = {
    'english-success': {
      "M1:Welcome to the Course": 'WDJlTaihMsY',
      "M1:Course Objectives": 'R09soFP3Qgk',
      "M1:Assessing Your English Level": 'cAhG7ojvS2k',
      "M1:Learning Strategies": '14o6hxpdWSg',
      "M1:Academic vs. Professional English": 'iHQuyCOGuag',
      "M1:Setting Language Goals": 'fVQ3CoTJczM',
      "M1:Study Plan": '07M-gotZCuA',
      "M2:Parts of Speech": 'v9fCKTwytJA',
      "M2:Sentence Structure": 'jul2urONzOQ',
      "M2:Nouns": 'gES-AewCOAI',
      "M2:Pronouns": 'gJrMkcWmt5g',
      "M2:Verbs": 'nEx49LO-j-c',
      "M2:Verb Tenses": 'HWjRVkTNoNM',
      "M2:Subject-Verb Agreement": '4NkXM1j3seA',
      "M2:Adjectives": 'qakXdVoPMT0',
      "M2:Adverbs": 'dKL26Gji4UY',
      "M2:Articles": 'Cc5i5jnqM4g',
      "M2:Prepositions": 'BD4Jf-AA1Fo',
      "M2:Conjunctions": '3qbfcHiUrcI',
      "M2:Modals": 'ZC710CZYv6k',
      "M2:Active & Passive Voice": 'CCqQi524HPg',
      "M2:Direct & Indirect Speech": 'wQIoo8OivsA',
      "M2:Conditionals": 'O_a-79E0ZUk',
      "M2:Relative Clauses": 'a_mFlafGyy8',
      "M2:Punctuation": 'zKLGW4AKerE',
      "M2:Common Grammar Errors": 'VF06PXnEz5s',
      "M3:Everyday Vocabulary": '5qiYEKVZAIM',
      "M3:Academic Vocabulary": '1VIZ3Xwhnm0',
      "M3:Professional Vocabulary": 'uD7Krhp50Ps',
      "M3:Business English Terms": 'u6tQgDcHv30',
      "M3:Word Formation": 'IslcIufzqYo',
      "M3:Prefixes & Suffixes": 'uc8AgRPyFe8',
      "M3:Synonyms & Antonyms": 'dfXA1D_5ad4',
      "M3:Collocations": 'gbIIuPrt_k0',
      "M3:Idioms": 'NQ4oAN3qbWQ',
      "M3:Phrasal Verbs": 'Emdc5LIhHa4',
      "M3:Context Clues": 'oO9CXNfo0-I',
      "M3:Vocabulary Building Strategies": '7XJJzA9KedY',
      "M4:Reading Strategies": 'W7BW9gv_OkU',
      "M4:Skimming": 'u5-EIeXskOs',
      "M4:Scanning": 'ZOS1NzVsHxI',
      "M4:Identifying Main Ideas": 'xiJnRybLBrs',
      "M4:Supporting Details": 'MwY4uqmx0qQ',
      "M4:Making Inferences": '-i7sHVSpr28',
      "M4:Vocabulary in Context": '-3mFnAk9sbw',
      "M4:Reading Academic Articles": 'ThCL_3GQZSc',
      "M4:Reading Business Documents": 'YjJEiWZw3_w',
      "M5:Active Listening": 'DXD3Ao7vlyc',
      "M5:Listening for Main Ideas": 'oolFQSzyHSg',
      "M5:Listening for Details": 'EX8RJR4-6PE',
      "M5:Note-Taking Skills": 'E7CwqNHn_Ns',
      "M5:Listening to Lectures": '3kxF1-jkz-U',
      "M5:Listening to Business Meetings": 'z-8o9sp8YIA',
      "M5:Understanding Different English Accents": 'wSYMMkLgno4',
      "M6:Pronunciation": 'zash7H0eMQ4',
      "M6:Intonation": 'rUY8LEMOYkQ',
      "M6:Fluency Development": 'CyxNdfv0YQA',
      "M6:Everyday Conversations": 'henIVlCPVIY',
      "M6:Academic Discussions": 'gmfc0rH9Lpg',
      "M6:Public Speaking": 'Ns_z4wEtdRM',
      "M6:Business Meetings": 'CQSBw4nb_98',
      "M6:Telephone Communication": 'P4Ph0Ct5HXc',
      "M6:Presentation Skills": 'BO0Gt5hoHU4',
      "M7:Sentence Writing": '4dr5lN1jqRE',
      "M7:Paragraph Writing": '2_pZWdF7ujA',
      "M7:Essay Writing": 'UuOWNNvupik',
      "M7:Academic Writing Style": 'BwQowyBUOYA',
      "M7:Writing Clearly and Concisely": 'n-rql1WFQ6k',
      "M7:Editing and Proofreading": 'pYb7p0DiVMI',
      "M8:Research Essays": '1LpVb3lYaKk',
      "M8:Reports": '4N7LlWsKlUw',
      "M8:Literature Reviews": 'zIYC6zG265E',
      "M8:Summaries": 'oDBabCxxulY',
      "M8:Paraphrasing": 'oiM0x0ApVL8',
      "M8:Referencing & Citations": 'jmIKlioF32Q',
      "M8:Avoiding Plagiarism": 'uQhVDH9p7aU',
      "M9:Business Emails": 'znDwZf3nUv4',
      "M9:Letters": 'egeyiUpFsaw',
      "M9:Memorandums": 'G_jErsVxjpM',
      "M9:Meeting Minutes": 'lmBWZAm90Vs',
      "M9:Reports": 'V8uF1EoIneE',
      "M9:Proposals": 'e6CNEFV2nkU',
      "M9:Resume (CV) Writing": 'ldsElF34YqM',
      "M9:Cover Letters": 'NUhDP30IRKk',
      "M9:LinkedIn Profile Writing": 'OKF7ZeWNrfg',
      "M10:Creating Presentation Slides": 'ex67_R6vC8c',
      "M10:Speaking with Confidence": 'lJXLLXdZC-Y',
      "M10:Body Language": 'U1O3UFeCEeU',
      "M10:Audience Engagement": 'paYdZ5SG2q4',
      "M10:Handling Questions": 'lfiNFNTwFGU',
      "M10:Presentation Practice": 'GaOWUTQ6RbI',
      "M11:Office Communication": 'TfWU_tl9KOE',
      "M11:Professional Etiquette": 'zLSpG1ywZB8',
      "M11:Team Collaboration": 'o9dEcZWxzHg',
      "M11:Giving & Receiving Feedback": 'pfhntb1j7Kk',
      "M11:Negotiation Skills": 'RfTalFEeKKE',
      "M11:Conflict Resolution": 'rXiMGT-Ie0M',
      "M11:Leadership Communication": 'hRKNGF95rN0',
      "M11:Workplace Scenarios": 't5o62DLau9A',
      "M12:Academic Research": 'LdQeaDN9Qic',
      "M12:Evaluating Sources": 'geRZjPUhJVA',
      "M12:Fact vs. Opinion": 'nKBzdtADTiY',
      "M12:Critical Reading": 'DWFZ6jMif6k',
      "M12:Critical Writing": 'V2EXDn2ZxMQ',
      "M12:Problem Solving": '6_LX9mo0Thw',
      "M12:Analytical Thinking": '8m52HxsgGP8',
      "M13:Online Research": 'LQ9brbqdO0A',
      "M13:Microsoft Word": '5Im87VPQZ_0',
      "M13:Google Docs": 'SAjmYGG52TA',
      "M13:Grammarly": 'FJ_ZWAUO78s',
      "M13:ChatGPT for Learning": 'XDYilxy1dn8',
      "M13:AI Writing Tools": '0dEyLCJPyeY',
      "M13:Responsible AI Use": 'zyf3YVWx6nw',
      "M13:Digital Collaboration": 'zdz0DjOx_Yc',
      "M14:Job Search Skills": 'JF0IukoW8to',
      "M14:Resume Writing": 'Tt08KmFfIYQ',
      "M14:Cover Letters": 'EcFOr9Jo0OA',
      "M14:Interview Preparation": 'eOnhw9q8Iw8',
      "M14:Workplace English": 'nmumGp6W5k8',
      "M14:Networking": 'RPAjy0bYNBA',
      "M14:Personal Branding": '1kUCm1JPzxg',
      "M14:Career Planning": 'fCNAubMwHew',
      "M15:Leadership Communication": 'al9bvOF_4VU',
      "M15:Emotional Intelligence": 'auXNnTmhHsk',
      "M15:Time Management": 'xgp6eELYY1M',
      "M15:Teamwork": 'GeFkmsyVlzQ',
      "M15:Decision Making": '2tCYy66CyuQ',
      "M15:Problem Solving": 'pGYh-_uEef4',
      "M15:Professional Ethics": 'AAExnpnwphs',
      "M15:Workplace Productivity": 'QHrWMMlVYRA',
      "M16:British English vs. American English": 'nzczj4XNCsk',
      "M16:Common International Expressions": 'Z12hu-K8Fio',
      "M16:Cross-Cultural Communication": 'lMplUEgo5YQ',
      "M16:English for Travel": 'DUqdQjkvElo',
      "M16:English for International Business": 'J7e_dJTHGrw',
      "M16:Global Workplace Communication": 'N3BFJVuOOwo',
      "M16:Intercultural Awareness": 'eSiLz4mkSL8',
      "M18:TOEFL Introduction": 'A6DuYv2mNzk',
      "M18:IELTS Introduction": 'IOke2dtZU9U',
      "M18:SAT Reading & Writing Overview": 'EZp4S_8K5Yo',
      "M18:Academic Vocabulary Review": 'r1u4GTI2FMs',
      "M18:Grammar Review": 'aUJO_0phvbw',
      "M18:Practice Tests": 'VUtUOTrJ2Kk',
      "M18:Test-Taking Strategies": 'Y_oC3jG58OY'
    },
    'toefl': {
      "M1:Welcome to the Course": 'VA2tNnTSs2A',
      "M1:How to Study Effectively": 'TjPFZaMe2yw',
      "M1:What is TOEFL?": 'YeVjkA22k7Y',
      "M1:TOEFL Test Structure": 'nvlx_QWtsQk',
      "M1:Scoring System": 'lGAqggcpE8Y',
      "M1:Study Plan": 'eAxu87t-4Rw',
      "M1:Test Registration": 'tHgeWQMyQS4',
      "M2:Parts of Speech": 'v9fCKTwytJA',
      "M2:Nouns": 'hnBfV4K1t0g',
      "M2:Pronouns": 'acqD-uZGMWc',
      "M2:Verbs": 'LciKb0uuFEc',
      "M2:Verb Tenses": 'Ljjiw9mC_Cg',
      "M2:Subject-Verb Agreement": '4NkXM1j3seA',
      "M2:Adjectives": '9KahrrivdQQ',
      "M2:Adverbs": 'jXtHCBgbks0',
      "M2:Prepositions": 'BD4Jf-AA1Fo',
      "M2:Conjunctions": 'xo7iVZHqJeY',
      "M2:Articles": 'Cc5i5jnqM4g',
      "M2:Active & Passive Voice": '8x4K9INW2Zg',
      "M2:Direct & Indirect Speech": 'wQIoo8OivsA',
      "M2:Conditional Sentences": 'O_a-79E0ZUk',
      "M2:Relative Clauses": 'oUw9qHAbcys',
      "M2:Modals": 'NrvA4eCqQ_M',
      "M2:Gerunds & Infinitives": 'kTmwW5AKI9A',
      "M2:Punctuation": 'ZSOikrKuyp0',
      "M2:Common Grammar Mistakes": 'VeFjw6nPD64',
      "M3:Academic Vocabulary": 'fE0W18Yz9hM',
      "M3:Word Formation": 'eB1jmIbPY_w',
      "M3:Prefixes & Suffixes": 'uc8AgRPyFe8',
      "M3:Synonyms": 'asN9bKf-H0w',
      "M3:Antonyms": 'kPELkTyZPE8',
      "M3:Collocations": 'CqRloBkyqQs',
      "M3:Idioms": 'VdRlvxcsD3Q',
      "M3:Phrasal Verbs": 'r7VKVXbaj_Y',
      "M3:Context Clues": 'CiNggzdWkIo',
      "M3:Vocabulary Review": '13apqCGGD60',
      "M4:Reading Strategies": 'eNkAaM9kDkA',
      "M4:Skimming": 'KLvt5hp1ZjA',
      "M4:Scanning": '-dT87rPsu1M',
      "M4:Main Ideas": 'dVSwh3wBVkU',
      "M4:Supporting Details": 'NvifImkq-aM',
      "M4:Vocabulary Questions": '0n-mJ8NvEwQ',
      "M4:Inference Questions": 'b2Xsn4K_JG4',
      "M4:Reference Questions": 'S7ih1dr9QQQ',
      "M4:Sentence Simplification": 's_g4uVhHIKQ',
      "M4:Summary Questions": 'A4aEd12QXLo',
      "M4:Reading Speed": 'Q6aZn8vjRcs',
      "M4:Timed Reading Practice": 'D4op4qp9MB0',
      "M5:Listening Strategies": 'fCncCQonO7A',
      "M5:Note-Taking": 'w_YCFu4vp4o',
      "M5:Campus Conversations": 'wDsc1gdmicA',
      "M5:Academic Lectures": 'K5XKJ8XfAHY',
      "M5:Main Idea Questions": 'Dh9P-es-_gY',
      "M5:Detail Questions": 'E-92q3nlD6E',
      "M5:Purpose Questions": 'XwrQ12HZzuY',
      "M5:Inference Questions": '5aT_VfOwb9U',
      "M5:Attitude Questions": 'rsX3JTgQVfQ',
      "M6:TOEFL Speaking Overview": 's6FKEbWzW1A',
      "M6:Independent Speaking": 'RUfPjA7UODU',
      "M6:Integrated Speaking": 'kkQRIDDPe7Q',
      "M6:Organizing Responses": 'WCUDBEP1zQc',
      "M6:Speaking Templates": 'YvpWvDk9H-U',
      "M6:Pronunciation": 'IF1CGkUcU18',
      "M6:Fluency": 'mlAOJE8Ag9o',
      "M6:Speaking Practice": 'JFCGkG2RIuc',
      "M7:Writing Overview": 'FC1j3hsxmdg',
      "M7:Integrated Writing": '7TMsVlWXlZE',
      "M7:Academic Discussion Writing": 'R4SduEOLfQk',
      "M7:Essay Structure": 'nUq2SG3ZuyQ',
      "M7:Thesis Statements": 'DFp1uGTXo4Q',
      "M7:Supporting Ideas": 'hi9-acR3AgY',
      "M7:Transitions": 'STiQ4BEV8ug',
      "M7:Editing": 'vWQESpoQbnk',
      "M7:Model Essays": 'WDNXsHUnyHk',
      "M8:English Sounds": 'xreA0vkHMBY',
      "M8:Stress": 'Vu6UVwkUgzc',
      "M8:Intonation": 'tzh3Owutf5Y',
      "M8:Connected Speech": 'gAHUTKm_1n0',
      "M8:Public Speaking Practice": 'p_zVwrFelBQ',
      "M9:Time Management": '_g5kYbLZmMY',
      "M9:Guessing Strategies": 'Q1y8c_MZYvE',
      "M9:Common Mistakes": 'R6IGfwA1Mco',
      "M9:Exam-Day Tips": 'S7s6rOT818o',
      "M9:Stress Management": 'SjNCi0wonkU'
    },
    'computer-literacy': {
      'M1:What Is a Computer?': 'WV46mRxdjiE',
      'M1:Types of Computers': '1wHT-dq7SG0',
      'M1:Parts of a Computer': 'VHhAZx4EvM8',
      'M1:Computer Hardware': 'RzQtbFb0KIk',
      'M1:Computer Software': 'FFjahRWzqTA',
      'M1:Hardware vs. Software': 'NARrnGza4kA',
      'M1:Input Devices': 'v7f3uG1OMMo',
      'M1:Output Devices': 'yl5Eq1VZa_U',
      'M1:Storage Devices': 'pcKXsXOhjpI',
      'M1:Computer Memory: RAM and ROM': 'E65t7RyGaoA',
      'M2:Starting and Shutting Down a Computer': 'Tx0ntUobTu8',
      'M2:Using the Keyboard': 'Bany7tvtuxI',
      'M2:Using a Computer Mouse': 'KNKgBBn_Fsg',
      'M2:Understanding the Desktop': 'L9lclLeCoYM',
      'M2:Using Windows Icons': 'LPZb5alBATQ',
      'M2:Using the Taskbar': 'yyK9ss9Xip8',
      'M2:Opening and Closing Programs': 'K5DxKV2gYAk',
      'M2:Using Windows Search': 'grZz-vTCue0',
      'M3:What Is an Operating System?': 'zFkgerr3x00',
      'M3:Introduction to Windows': 'xz8W7yh3BBM',
      'M3:Windows Desktop': 'GDKIxBr6yhI',
      'M3:Windows Settings': 'e5rQudFMF7Q',
      'M3:Control Panel': 'U40Kz0ZZYDA',
      'M3:Installing Software': 'J-UUJH_3eGg',
      'M3:Uninstalling Software': 'WPMujL6MeOE',
      'M3:Windows Updates': 'OMn6iEOIR2g',
      'M4:What Are Files and Folders?': 'WqRTgpjsarA',
      'M4:Creating a Folder': 's59UcOn0dcE',
      'M4:Renaming Files and Folders': '1Sq1Zp5yGO4',
      'M4:Copying and Moving Files': 'gTIFvdAsHjI',
      'M4:Deleting Files and Folders': 'Wli4eR_J89M',
      'M4:Using Recycle Bin': 'xwMGKhik2yQ',
      'M4:Searching for Files': 'Ym8Pzh63WVw',
      'M4:Organizing Your Files': 'HDmwiJxzIrw',
      'M5:What Is the Internet?': 'qRZ-970JaLc',
      'M5:How the Internet Works': 'qRZ-970JaLc',
      'M5:What Is a Web Browser?': 'zuRofKQJleA',
      'M5:Using Google Chrome': '5Vd2GHS7Po8',
      'M5:Using Search Engines': 'wn4BUsjJZzo',
      'M5:Effective Google Searching': 'Z9n3VPTQYqo',
      'M5:Opening and Managing Web Pages': 'YVJjZG7kosg',
      'M5:Downloading Files From the Internet': 'XeYPa7XBrbI',
      'M6:Internet Safety Basics': '9VcuvrKWaJk',
      'M6:Creating Strong Passwords': '3NjQ9b3pgIg',
      'M6:Two-Factor Authentication': '0mvCeNsTa1g',
      'M6:Recognizing Phishing Scams': 'P0HeMNM6veI',
      'M6:Avoiding Online Scams': 'dmm3pIxNDNU',
      'M6:Protecting Personal Information Online': 'ArGtqbwfP5o',
      'M6:Safe Downloads': 'GKGzN76lrvo',
      'M6:Computer Viruses and Malware': 'cFo5D9mFUJQ',
      'M7:What Is Email?': 'PEB9jEXh0X4',
      'M7:Creating a Gmail Account': 'RxRgbKmnaos',
      'M7:Understanding the Gmail Interface': '1lP22jySvDE',
      'M7:Sending an Email': 'zXrDvZ8hhY4',
      'M7:Replying to an Email': 'PCV5aPvdBYI',
      'M7:Email Attachments': '29xVC9o_orM',
      'M7:Managing Email': 'oLdHnWLbn4A',
      'M7:Email Etiquette': 'fMV7fFh_ZuM',
      'M8:Introduction to Microsoft Word': '5eTKElZLM9Q',
      'M8:Creating a Word Document': 'Iwg1VB3IusA',
      'M8:Typing and Editing Text': 'N5HpQrL77uQ',
      'M8:Formatting Text': 'pmAl-8Tf8Pg',
      'M8:Using Styles and Headings': 'rpXzLKcyxHM',
      'M8:Creating Lists': 'wLbHCy3k8aI',
      'M8:Inserting Pictures': 'q92QGiWVmGE',
      'M8:Creating Tables': 'JFyvHnaVGtM',
      'M8:Page Layout and Margins': '-vmofXKfsuM',
      'M8:Headers, Footers and Page Numbers': 'sHpf-lqQbqI',
      'M8:Saving a Word Document': 'oRfKX1H19JQ',
      'M8:Printing and Saving as PDF': 'fAG_lSrJWl0',
      'M9:Introduction to Microsoft Excel': 'wbJcJCkBcMg',
      'M9:Understanding the Excel Interface': 'SOvI2_dL02Q',
      'M9:Workbooks and Worksheets': 'I7j-Hf0v3nA',
      'M9:Rows, Columns and Cells': 'rToJbe2wcnY',
      'M9:Entering Data': 'eZXON7NssQ0',
      'M9:Formatting Cells': 'OmA6l7xwNHo',
      'M9:Basic Excel Formulas': 'ZwiQ0W5lTEg',
      'M9:Excel Functions': 'C5i70r3iEzA',
      'M9:Sorting Data': 'WUTElsPoyZM',
      'M9:Filtering Data': 'BtiVbY7lhqw',
      'M9:Creating Charts': '64DSXejsYbo',
      'M9:Creating a Simple Spreadsheet Project': 'EPnKHPEKjBU',
      'M10:Introduction to Microsoft PowerPoint': '0M6pJFfS2L4',
      'M10:Understanding the PowerPoint Interface': 'Kcz1meue8PE',
      'M10:Creating a Presentation': 'l5Ij7nUy9UQ',
      'M10:Adding and Editing Slides': 'JBqTihRhFQg',
      'M10:Adding Text and Images': 'EhBoJ6tiizw',
      'M10:Themes and Templates': 'aHhtjMSGRe0',
      'M10:Slide Transitions': 'kbPybHG2kCk',
      'M10:Animations': '3uJd-_JpG1w',
      'M10:Adding Audio and Video': 'g6JuY91Tis0',
      'M10:Presenting a Slide Show': 'XGbSyYcj-z8',
      'M11:What Is Google Workspace?': 'jOTQR6Hqjoo',
      'M11:Google Drive': 'gdrxAoqfvbA',
      'M11:Uploading Files to Google Drive': 'luH4t1kZ5CA',
      'M11:Organizing Google Drive Files': 'ncMhCwc0Wn4',
      'M11:Sharing Files and Folders': '_8WfSm6opKo',
      'M11:Google Docs': 'eIMm6n63j8Q',
      'M11:Google Sheets': '7gVq4xA7q2Y',
      'M11:Google Slides': '8hO6M6H4JmA',
      'M12:Introduction to Google Meet': 'VV0wf3ssKqc',
      'M12:Joining a Google Meet Meeting': '6dWHR82q1Dw',
      'M12:Creating a Google Meet Meeting': 'nmB-Hy4flTM',
      'M12:Using the Camera and Microphone': 'bFIFFIN-_4I',
      'M12:Sharing Your Screen': 'DwJgHsjIIK4',
      'M12:Introduction to Zoom': 'QOUwumKCW7M',
      'M12:Joining a Zoom Meeting': 'DxIBTi-xxrg',
      'M12:Using Zoom for Online Classes and Meetings': 'vFlaxmCeQS8',
      'M13:Keeping Your Computer Clean and Organized': '4quw0vggDxw',
      'M13:Installing and Updating Software': 'ZbLTOPGPjgk',
      'M13:Windows Updates': 'OMn6iEOIR2g',
      'M13:Backing Up Important Files': 'OfNqHYdZZCA',
      'M13:Managing Computer Storage': 'wvN6HItL5YM',
      'M13:Basic Computer Troubleshooting': 'gie6tXhTtDk',
      'M13:Common Windows Problems': 'aIokkVNHwrA',
      'M13:Safe Computer Maintenance': 'FEdC_Np6jUs',
      'M14:Creating a Professional Document': 'T4N4AXOChOE',
      'M14:Creating a Professional Spreadsheet': 'EPnKHPEKjBU',
      'M14:Creating a Professional Presentation': 'l5Ij7nUy9UQ',
      'M14:Professional Email Communication': '3fTTu5uyeYU',
      'M14:Managing Digital Files': 'LMFP3-qF6UE',
      'M14:Online Collaboration': 'UGowQt4E2PM',
      'M14:Digital Workplace Safety': 'E7-8rGrjcnw'
    },
    'ai-cybersecurity': {
      'M1:What Is Artificial Intelligence?': 'ad79nYk2keg',
      'M1:What Is Cybersecurity?': 'inWWhr5tnEA',
      'M1:Why AI and Cybersecurity Matter': '2ePf9rue1Ao',
      'M1:Types of Cyber Threats': '0o8axKc4j9A',
      'M1:Cybersecurity Roles and Careers': 'U_P23SqJaDc',
      'M1:How AI Is Used in Cybersecurity': '2ePf9rue1Ao',
      'M2:Computer Hardware and Software': 'Xpk67YzOn5w',
      'M2:Operating Systems': '26QPDBe-NB8',
      'M2:Files, Processes, and Services': 'ZtqBQ68cfJc',
      'M2:What Is a Computer Network?': 'IHdXfUHBBEI',
      'M2:IP Addresses': '8zEVA-Bxs-0',
      'M2:MAC Addresses': '-DxV9mluqc8',
      'M2:DNS and DHCP': 'BYN4qJjb484',
      'M2:Ports and Protocols': '4ZtZ1N5K9kM',
      'M2:TCP/IP Fundamentals': 'tnAW02zvFhU',
      'M2:How the Internet Works': '7_LPdttKXPc',
      'M3:CIA Triad: Confidentiality, Integrity and Availability': 'pAGcgMfVykg',
      'M3:Authentication and Authorization': 'pAGcgMfVykg',
      'M3:Password Security': '3NjQ9b3pgIg',
      'M3:Multi-Factor Authentication': '0mvCeNsTa1g',
      'M3:Encryption Basics': 'AQDCe585Lnc',
      'M3:Firewalls': 'kDEX1HXybrU',
      'M3:Antivirus and Endpoint Security': '4f4k3QZ7j0I',
      'M3:Security Policies': '6Z7N9R1Q1wM',
      'M3:Risk Management': '0j3J5m7W9bM',
      'M3:Security Awareness': 'XBkzBrXlle0',
      'M4:What Is Linux?': '-E97kKJTBxc',
      'M4:Installing a Linux Virtual Machine': 'wX75Z-4MEoM',
      'M4:Linux Terminal Basics': 'oxuRxtrO2Ag',
      'M4:Linux File System': 'HbgzrKJvDRw',
      'M4:Users and Permissions': 'iwolPf6kN-k',
      'M4:Managing Processes': '6gN2f3W4v7k',
      'M4:Installing Software': 'V3s6rK6s5kY',
      'M4:Networking Commands': '9GDX-IyZ_C8',
      'M4:Bash Fundamentals': 'tK9Oc6AEnR4',
      'M4:Linux Security Basics': 'J2zQmJ8b6vA',
      'M5:What Is Ethical Hacking?': 'XLvPpirlmEs',
      'M5:Legal and Ethical Responsibilities': '0Qq4j2H7G4Y',
      'M5:Reconnaissance': 'Q2J6FfV9z9k',
      'M5:Information Gathering': 'Q2J6FfV9z9k',
      'M5:Vulnerability Scanning': '5jG3h4p7n2A',
      'M5:Network Scanning': '4t4kBkMsDbQ',
      'M5:Understanding Common Vulnerabilities': 'QJ6gY1Q9v8Y',
      'M5:Web Security Fundamentals': '1w6QZ7p9n2M',
      'M5:Password Security Testing': '7U-RfR6J3jM',
      'M5:Writing a Security Assessment': 'V0p8yQ3m2Lk',
      'M6:How Websites Work': 'hJHvdBlSxug',
      'M6:HTTP and HTTPS': 'iYM2zFP3Zn0',
      'M6:Cookies and Sessions': 'IF3Z7X2Q4vM',
      'M6:Authentication Security': '9b5Z6r8m1KQ',
      'M6:Access Control': 'V6X5X3m9rYQ',
      'M6:SQL Injection Concepts': 'ciNHn38EyRc',
      'M6:Cross-Site Scripting (XSS)': 'EoaDgUgS6QA',
      'M6:Cross-Site Request Forgery (CSRF)': '3w1G7Q4Y2jA',
      'M6:Secure Web Development': 'F7Kz5Y1r9Qk',
      'M6:OWASP Top 10': 'Zp4B5m7N8xQ',
      'M7:Introduction to Python': 'rfscVS0vtbw',
      'M7:Installing Python': 'YYXdXT2l-Gg',
      'M7:Python Variables and Data Types': 'ohCDWZgNIU0',
      'M7:Conditions and Loops': '6iF8Xb7Z3wQ',
      'M7:Functions': 'NSbOtYzIQI0',
      'M7:Working With Files': 'Uh2ebFW8OYM',
      'M7:Python and Networking': 'Qnagf4K4Ju8',
      'M7:Working With APIs': 'WXsD0ZgxjRw',
      'M7:Automating Security Tasks': 'Qnagf4K4Ju8',
      'M7:Building a Simple Security Tool': 'Qnagf4K4Ju8',
      'M8:AI vs. Machine Learning': '4qVRBYAdLAo',
      'M8:Generative AI': 'G2fqAlgmoPo',
      'M8:Large Language Models': 'zjkBMFhNj_g',
      'M8:How ChatGPT and Similar AI Systems Work': 'OX2pW9n6Q0I',
      'M8:Prompt Engineering': '_ZvnD73m40o',
      'M8:AI for Security Research': '2ePf9rue1Ao',
      'M8:AI for Log Analysis': '9RfsRn7m7OE',
      'M8:AI for Threat Detection': '2ePf9rue1Ao',
      'M8:AI-Assisted Security Automation': '2ePf9rue1Ao',
      'M8:Limitations of AI in Cybersecurity': '2ePf9rue1Ao',
      'M9:Understanding Security Logs': '9RfsRn7m7OE',
      'M9:Identifying Suspicious Activity': '9RfsRn7m7OE',
      'M9:Detecting Anomalies': '9RfsRn7m7OE',
      'M9:AI-Based Malware Detection': '2ePf9rue1Ao',
      'M9:Phishing Detection With AI': 'XBkzBrXlle0',
      'M9:Threat Intelligence': '8eG4mL8Y6jA',
      'M9:Indicators of Compromise (IOCs)': '6X5V8Q4m2jA',
      'M9:Security Event Analysis': '9RfsRn7m7OE',
      'M9:Building a Basic Threat Detection Workflow': '9RfsRn7m7OE',
      'M9:Evaluating AI Security Tools': '2ePf9rue1Ao',
      'M10:What Is a SOC?': '8dR5D4Y3jQk',
      'M10:SOC Analyst Responsibilities': 'U_P23SqJaDc',
      'M10:Security Information and Event Management (SIEM)': '9RfsRn7m7OE',
      'M10:Log Collection': '9RfsRn7m7OE',
      'M10:Alert Monitoring': '9RfsRn7m7OE',
      'M10:Alert Triage': '9RfsRn7m7OE',
      'M10:Incident Investigation': '9RfsRn7m7OE',
      'M10:Threat Hunting': '6X5V8Q4m2jA',
      'M10:Incident Documentation': 'V0p8yQ3m2Lk',
      'M10:SOC Automation': '9RfsRn7m7OE',
      'M12:AI-Generated Phishing': 'XBkzBrXlle0',
      'M12:Deepfakes and Identity Fraud': '4Q7FTjhvZ7Y',
      'M12:AI-Powered Social Engineering': '2ePf9rue1Ao',
      'M12:Adversarial Machine Learning': '1KqW9v9L3rA',
      'M12:Prompt Injection': '9RfsRn7m7OE',
      'M12:AI Data Privacy': '2ePf9rue1Ao',
      'M12:Securing AI Applications': '2ePf9rue1Ao',
      'M12:AI Model Security': '2ePf9rue1Ao',
      'M12:Responsible AI': '2ePf9rue1Ao',
      'M12:Future of AI and Cybersecurity': '2ePf9rue1Ao',
      'M13:What Is Cloud Computing?': 'RWgW-CgdIk0',
      'M13:Cloud Security Fundamentals': 'K4r9Q5j7m2A',
      'M13:Identity and Access Management': 'T5c7m2L9Q1A',
      'M13:Cloud Data Protection': 'K4r9Q5j7m2A',
      'M13:Cloud Network Security': 'K4r9Q5j7m2A',
      'M13:Securing Cloud Applications': 'K4r9Q5j7m2A',
      'M13:AI Services in the Cloud': '2ePf9rue1Ao',
      'M13:Cloud Security Monitoring': '9RfsRn7m7OE',
      'M13:Common Cloud Security Risks': 'K4r9Q5j7m2A',
      'M13:Cloud Security Best Practices': 'K4r9Q5j7m2A'
    },
    'ph-career': {
      "M1:Welcome to the Course": "5aww-Bpgkf4",
      "M1:The Public Health Job Market in West Africa": "iYSZoemyndk",
      "M1:Career Pathways in Public Health": "G8rx-drU6r4",
      "M1:Key Public Health Job Roles": "83BVNZWLrtM",
      "M1:Assessing Your Skills and Strengths": "yLfYa3PGTGM",
      "M1:Setting SMART Career Goals": "1DYM7Rq9GnY",
      "M1:Building Your Career Plan": "RM6xvMq1pm4",
      "M2:Epidemiology Essentials": "_luU3I03JwE",
      "M2:Biostatistics and Data Literacy": "7CqolAC_owc",
      "M2:Disease Surveillance": "3IpE8dE4cVc",
      "M2:Health Promotion and Education": "9Kmf7dblI9s",
      "M2:Health Systems and Policy": "yIS2h__uezE",
      "M2:Environmental and Occupational Health": "4zdVtEgSuVs",
      "M2:Global Health and One Health": "2rfRk_mTf7M",
      "M3:Writing a Public Health CV": "pS3oXPewvnE",
      "M3:Writing a Cover Letter": "xcdvRKbSOY0",
      "M3:Personal Statements and Motivation Letters": "PYVt0k_xS98",
      "M3:Building a Professional Portfolio": "OJ_p_djn1pI",
      "M3:Creating a Strong LinkedIn Profile": "27BTcka64wQ",
      "M3:References and Recommendation Letters": "CpRVeSXwL2o",
      "M4:Where to Find Public Health Jobs": "FvN1rfxYKIo",
      "M4:Working with NGOs and INGOs": "DgGe-ufSudQ",
      "M4:Ministry of Health and Government Roles": "4azlLbHrNDA",
      "M4:WHO, UN and International Agencies": "3d14-zm0nGY",
      "M4:Fellowships, Internships and Volunteering": "YqH8AHS-JFY",
      "M4:Networking for Public Health Professionals": "IO5Ht7yV_0A",
      "M4:Using Job Boards and Alerts": "8bObZXHkXL0",
      "M5:Preparing for a Public Health Interview": "KukmClH1KoA",
      "M5:Common Interview Questions and Answers": "5h-XvgSPSTc",
      "M5:Behavioral (STAR) Interviews": "xulpDyBxDgk",
      "M5:Technical and Case Interviews": "qNYr4A-ihFc",
      "M5:Virtual and Panel Interviews": "4OTDvU4vQEI",
      "M5:Salary Negotiation": "jDCxSKUeo6U",
      "M5:Following Up After an Interview": "jA9VgHeH2jw",
      "M6:Monitoring and Evaluation (M&E)": "cLMALnDc87E",
      "M6:Project and Program Management": "0zF06TOKKOE",
      "M6:Grant and Proposal Writing": "ByQRri_LTUE",
      "M6:Report Writing": "ReJBeUdfp7Y",
      "M6:Data Collection Tools (KoBoToolbox & ODK)": "fTNrHV9Geqs",
      "M6:Data Analysis with Excel and SPSS": "yjnaxBz-r2o",
      "M6:Community Engagement and Mobilization": "YAc-9vf9r5Y",
      "M6:Building Data Dashboards": "8VyKSn4Xuk0",
      "M7:Scientific and Technical Writing": "Twc2S88zuGo",
      "M7:Presenting Data and Findings": "aEnWzdMU65A",
      "M7:Writing Policy Briefs": "wuc3eNsPirM",
      "M7:Public Speaking and Presentations": "-FOCpMAww28",
      "M7:Facilitating Meetings and Trainings": "novrXP6AUqQ",
      "M7:Working with the Media and the Public": "S_z5qkF-5V4",
      "M8:Continuing Education and Certifications": "ARyEmpUkCc0",
      "M8:Applying for an MPH or PhD Abroad": "3ejMdAcoe48",
      "M8:Leadership and Management Skills": "3euwKJ5NWlQ",
      "M8:Professional Ethics and Integrity": "8raZzBD4Bl0",
      "M8:Mentorship: Finding and Being a Mentor": "PKS_cRfHArc",
      "M8:Work-Life Balance and Avoiding Burnout": "j-ypP1g4ba4",
      "M8:Building a Lasting Professional Network": "5BesUAyNvFY"
    }
  };
  function normMap(src){var out={};Object.keys(src||{}).forEach(function(cid){out[cid]={};Object.keys(src[cid]).forEach(function(k){var id=vid(src[cid][k]);if(id)out[cid][k]=id;});});return out;}
  window.TIH_MODULE_VIDEOS = normMap(MODULES);
  window.TIH_TOPIC_VIDEOS = normMap(TOPICS);
})();
