const {app,BrowserWindow,protocol,net,ipcMain,dialog,session,Menu}=require('electron');const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');const {defaults,validate,merge,assetPath}=require('./model.cjs');
protocol.registerSchemesAsPrivileged([{scheme:'tih',privileges:{standard:true,secure:true,supportFetchAPI:true,corsEnabled:true}}]);
let window,store;const origin='tih://app';
function read(){try{return validate(JSON.parse(fs.readFileSync(store,'utf8')));}catch(e){if(e.code==='ENOENT')return defaults();throw Error('Your study file could not be read. Restore a backup or contact TIH; the file has not been overwritten.');}}
function write(data){const value=validate(data);fs.mkdirSync(path.dirname(store),{recursive:true});fs.writeFileSync(store+'.tmp',JSON.stringify(value));fs.renameSync(store+'.tmp',store);return value;}
function trusted(event){if(event.sender!==window.webContents||event.senderFrame!==window.webContents.mainFrame||!event.senderFrame.url.startsWith(origin+'/'))throw Error('Untrusted request');}
app.whenReady().then(()=>{store=path.join(app.getPath('userData'),'study-workspace.json');const root=path.join(__dirname,'src');protocol.handle('tih',request=>{try{return net.fetch(pathToFileURL(assetPath(request.url,root)).href);}catch{return new Response('Not found',{status:404});}});
session.defaultSession.setPermissionRequestHandler((_w,_p,cb)=>cb(false));session.defaultSession.setPermissionCheckHandler(()=>false);
ipcMain.handle('study:read',e=>{trusted(e);return read();});ipcMain.handle('study:write',(e,data)=>{trusted(e);return write(data);});
ipcMain.handle('study:export',async e=>{trusted(e);const result=await dialog.showSaveDialog(window,{title:'Back up your TIH workspace',defaultPath:'TIH-Learning-backup.json',filters:[{name:'TIH workspace',extensions:['json']}]});if(result.canceled)return false;fs.writeFileSync(result.filePath,JSON.stringify(read(),null,2));return true;});
ipcMain.handle('study:import',async e=>{trusted(e);const result=await dialog.showOpenDialog(window,{title:'Restore a TIH workspace backup',properties:['openFile'],filters:[{name:'TIH workspace',extensions:['json']}]});if(result.canceled)return null;const p=result.filePaths[0];if(fs.statSync(p).size>8*1024*1024)throw Error('Backup is too large.');return write(merge(read(),JSON.parse(fs.readFileSync(p,'utf8'))));});
window=new BrowserWindow({width:1440,height:960,minWidth:960,minHeight:700,title:'TIH Learning Desktop',backgroundColor:'#f5f7fb',icon:path.join(root,'content/logo.png'),webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});
window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',(event,url)=>{if(!url.startsWith(origin+'/'))event.preventDefault();});window.webContents.on('will-attach-webview',event=>event.preventDefault());Menu.setApplicationMenu(null);window.loadURL(origin+'/index.html');
});app.on('window-all-closed',()=>app.quit());
