const crypto=require('node:crypto');
const defaults=()=>({version:1,name:'',saved:[],notes:[],completed:[],goal:25,fontSize:18,lastLesson:''});
function validate(value){if(!value||typeof value!=='object'||Array.isArray(value)||value.version!==1)throw Error('This is not a TIH desktop backup.');
if(Array.isArray(value.notes)&&(value.notes.length>200||value.notes.some(n=>!n||typeof n.id!=='string'||!/^[-a-zA-Z0-9]{1,80}$/.test(n.id))||new Set(value.notes.map(n=>n.id)).size!==value.notes.length))throw Error('Backup notes are invalid or exceed the 200-note limit.');
const text=(v,max)=>typeof v==='string'?v.slice(0,max):'';const ids=v=>Array.isArray(v)?[...new Set(v.filter(x=>typeof x==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(x)))].slice(0,200):[];
return {version:1,name:text(value.name,50),lastLesson:ids([value.lastLesson])[0]||'',saved:ids(value.saved),completed:ids(value.completed),goal:[15,25,45,60].includes(value.goal)?value.goal:25,fontSize:[16,18,20,22].includes(value.fontSize)?value.fontSize:18,notes:(Array.isArray(value.notes)?value.notes:[]).slice(0,200).filter(n=>n&&typeof n.id==='string').map(n=>({id:text(n.id,80),title:text(n.title,120),body:text(n.body,30000),courseId:text(n.courseId,80),updatedAt:Number.isFinite(n.updatedAt)?n.updatedAt:0}))};}
function merge(a,b){a=validate(a);b=validate(b);const notes=new Map(a.notes.map(n=>[n.id,n]));for(const n of b.notes){const old=notes.get(n.id);if(!old)notes.set(n.id,n);else if(old.body!==n.body||old.title!==n.title){const id=crypto.randomUUID();notes.set(id,{...n,id,title:n.title+' (imported)'});}}return validate({...a,saved:[...a.saved,...b.saved],completed:[...a.completed,...b.completed],notes:[...notes.values()]});}
function assetPath(url,root){const path=require('node:path');const u=new URL(url);if(u.protocol!=='tih:'||u.hostname!=='app')throw Error('Invalid origin');const p=decodeURIComponent(u.pathname);const resolved=path.resolve(root,'.'+p);if(resolved!==root&&!resolved.startsWith(root+path.sep))throw Error('Invalid path');return resolved;}
module.exports={defaults,validate,merge,assetPath};
