const crypto=require('node:crypto');
const defaults=()=>({version:1,name:'',saved:[],notes:[],completed:[],goal:25,fontSize:18,lastLesson:'',activeCourse:'computer-literacy',courseBookmarks:{},quizScores:{},quizDrafts:{},projects:{}});
function validate(value){if(!value||typeof value!=='object'||Array.isArray(value)||value.version!==1)throw Error('This is not a TIH desktop backup.');
if(Array.isArray(value.notes)&&(value.notes.length>500||value.notes.some(n=>!n||typeof n.id!=='string'||!/^[-a-zA-Z0-9]{1,80}$/.test(n.id))||new Set(value.notes.map(n=>n.id)).size!==value.notes.length))throw Error('Backup notes are invalid or exceed the 500-note limit.');
const text=(v,max)=>typeof v==='string'?v.slice(0,max):'';const ids=v=>Array.isArray(v)?[...new Set(v.filter(x=>typeof x==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(x)))].slice(0,5000):[];
const records=(v,map)=>Object.fromEntries(Object.entries(v&&typeof v==='object'&&!Array.isArray(v)?v:{}).filter(([id])=>/^[-a-zA-Z0-9]{1,80}$/.test(id)).slice(0,5000).map(([id,x])=>[id,map(x)]));
const score=(v,max)=>Number.isFinite(v)?Math.max(0,Math.min(max,Math.floor(v))):0;
const quizScores=records(value.quizScores,x=>({best:score(x?.best,100),last:score(x?.last,100),attempts:score(x?.attempts,10000),updatedAt:Number.isFinite(x?.updatedAt)?x.updatedAt:0,answers:Array.isArray(x?.answers)?x.answers.slice(0,100).map(a=>Number.isInteger(a)&&a>=0&&a<20?a:-1):[]}));
const quizDrafts=records(value.quizDrafts,x=>Array.isArray(x)?x.slice(0,100).map(a=>Number.isInteger(a)&&a>=0&&a<20?a:-1):[]);
const projects=records(value.projects,x=>({body:text(x?.body,10000),files:text(x?.files,1000),complete:x?.complete===true&&text(x?.body,10000).trim().length>=20,updatedAt:Number.isFinite(x?.updatedAt)?x.updatedAt:0}));
const courseBookmarks=Object.fromEntries(Object.entries(value.courseBookmarks||{}).filter(([id,l])=>['computer-literacy','ielts'].includes(id)&&ids([l]).length).map(([id,l])=>[id,ids([l])[0]]));
return {version:1,activeCourse:['computer-literacy','ielts'].includes(value.activeCourse)?value.activeCourse:'computer-literacy',courseBookmarks,quizScores,quizDrafts,projects,name:text(value.name,50),lastLesson:ids([value.lastLesson])[0]||'',saved:ids(value.saved),completed:ids(value.completed),goal:[15,25,45,60].includes(value.goal)?value.goal:25,fontSize:[16,18,20,22].includes(value.fontSize)?value.fontSize:18,notes:(Array.isArray(value.notes)?value.notes:[]).slice(0,500).filter(n=>n&&typeof n.id==='string').map(n=>({id:text(n.id,80),title:text(n.title,120),body:text(n.body,30000),courseId:text(n.courseId,80),updatedAt:Number.isFinite(n.updatedAt)?n.updatedAt:0}))};}
function merge(a,b){a=validate(a);b=validate(b);const notes=new Map(a.notes.map(n=>[n.id,n]));for(const n of b.notes){const old=notes.get(n.id);if(!old)notes.set(n.id,n);else if(old.body!==n.body||old.title!==n.title){const id=crypto.randomUUID();notes.set(id,{...n,id,title:n.title+' (imported)'});}}const scores={...a.quizScores};for(const [id,s] of Object.entries(b.quizScores)){const old=scores[id];scores[id]={...(old&&old.updatedAt>s.updatedAt?old:s),best:Math.max(old?.best||0,s.best),attempts:Math.max(old?.attempts||0,s.attempts)};}const projects={...a.projects};for(const [id,p] of Object.entries(b.projects)){const old=projects[id];if(old&&old.body!==p.body&&p.body){const noteId=crypto.randomUUID();notes.set(noteId,{id:noteId,title:'Imported project reflection',body:p.body+'\nFiles: '+p.files,courseId:id,updatedAt:p.updatedAt});}else if(!old||old.updatedAt<p.updatedAt)projects[id]=p;}return validate({...a,courseBookmarks:{...b.courseBookmarks,...a.courseBookmarks},quizScores:scores,quizDrafts:{...b.quizDrafts,...a.quizDrafts},projects,saved:[...a.saved,...b.saved],completed:[...a.completed,...b.completed],notes:[...notes.values()]});}
function assetPath(url,root){const path=require('node:path');const u=new URL(url);if(u.protocol!=='tih:'||u.hostname!=='app')throw Error('Invalid origin');const p=decodeURIComponent(u.pathname);const resolved=path.resolve(root,'.'+p);if(resolved!==root&&!resolved.startsWith(root+path.sep))throw Error('Invalid path');return resolved;}
module.exports={defaults,validate,merge,assetPath};
