/* TIH IELTS Mastery — one distinct video per topic.
   Keys are module-qualified (M<n>:<topic title>) so a repeated title still
   gets its own clip. Loaded on demand by tih-video-runtime.js. */
window.TIH_TOPIC_VIDEOS = window.TIH_TOPIC_VIDEOS || {};
window.TIH_TOPIC_VIDEOS["ielts"] = {

  "M1:The IELTS Test: Academic vs General Training": "2_4Nf95bTjs",
  "M1:Understanding the Band Score System (0\u20139)": "zBLsjez-D3s",
  "M1:Test-Day Logistics & Smart Preparation": "nxMFZMBWWC0",

  "M2:The Four Sections & Every Question Type": "Z16XUXJyVIk",
  "M2:Strategies: Prediction, Keywords & Distractor Traps": "jtIyTN48iL0",
  "M2:Spelling, Numbers & Transferring Answers": "qvYGMmjDIAY",

  "M3:Skimming, Scanning & Time Management": "7etaXjWJVJg",
  "M3:True / False / Not Given (and Yes / No / Not Given)": "Cw7G8-QaWCQ",
  "M3:Matching Headings, Completion & Multiple Choice": "SXdMpskBDmA",

  "M4:Task 1 Academic: Describing Graphs, Charts & Processes": "D2q6wxf7hkQ",
  "M4:Task 1 General: Formal & Informal Letters": "TbdP4Sz5Bn0",
  "M4:Task 2: Essay Structure & Building an Argument": "sA8bE2QxY3o",
  "M4:Cohesion, Vocabulary & Common Mistakes": "2WdSGHi7VXM",

  "M5:Part 1: Introduction & Interview": "jQ3XwXsHWW4",
  "M5:Part 2: The Long Turn (Cue Card)": "BzhUwBaQK1g",
  "M5:Part 3: Discussion, Fluency & Pronunciation": "acZnayamqso",

  "M6:Vocabulary for Band 7+: Collocations & Precision": "ncS6Z7WhcVw",
  "M6:Grammar Range: Complex Sentences Without Errors": "L0eHrSC5zYA",
  "M6:The Full Mock Test: Practice Under Real Exam Conditions": "NXJa7GFjY3U",
  "M6:Your 30-Day Study Plan & Test-Week Checklist": "QS4LK13AV-c",

  "M7:English Alphabet & Pronunciation": "MuTRI3-k0do",
  "M7:Basic Grammar": "IaslvsYxFVU",
  "M7:Parts of Speech": "SceDmiBEESI",
  "M7:Common Vocabulary": "5qiYEKVZAIM",
  "M7:Sentence Structure": "OserH3YLBgg",
  "M7:Daily Conversations": "-iR47SMAreA",
  "M7:Greetings & Introductions": "7aWhs5G6I-I",
  "M7:Numbers, Dates & Time": "_J9hRZ1OAjU",
  "M7:Family & Friends": "_heLgt7M1eg",
  "M7:Describing People": "uMkJ4qcx5iw",

  "M8:Listening for Names and Numbers": "MgWfkrMOhV0",
  "M8:Listening for Directions": "OjLzrpCq__U",
  "M8:Everyday Conversations": "-cO122c906I",
  "M8:Understanding Simple Instructions": "BkAR5Vhds50",
  "M8:Note Completion Practice": "aQAcJbZ7Iyg",
  "M8:Form Completion Practice": "aS5ysI70TLU",

  "M9:Skimming and Scanning": "0FvwDs8QKt0",
  "M9:Finding Main Ideas": "xiJnRybLBrs",
  "M9:Reading Advertisements": "e93cHwysVzs",
  "M9:Reading Emails and Messages": "nPc9LI2Yq9A",
  "M9:Reading Short Articles": "hv57Tx5KWNA",
  "M9:Vocabulary Building": "or8YpOLqacU",

  "M10:Sentence Writing": "gNpZY6G4uPc",
  "M10:Paragraph Writing": "IqxuNrhKhMc",
  "M10:Describing People": "N3PnAH-vO7c",
  "M10:Describing Places": "SmSRH7kpdYA",
  "M10:Writing Informal Emails": "llqPvcciKEM",
  "M10:Common Grammar Errors": "soN1qPcSDVo",

  "M11:Self-Introduction": "98pM_i_sklo",
  "M11:Talking About Family": "DtRChA8DUdQ",
  "M11:Talking About Hobbies": "8NGVXvgl-d8",
  "M11:Talking About School": "DjA3naFOTvc",
  "M11:Talking About Work": "D-ukmakW6Vs",
  "M11:Basic Fluency Practice": "FFxbvib6aVw",

  "M12:Multiple Choice Questions": "3oQNETB8RdA",
  "M12:Map Labelling": "1LuGkszzKHs",
  "M12:Table Completion": "34s3TeauAkc",
  "M12:Sentence Completion": "xeG-2_jfpbE",
  "M12:Summary Completion": "Jtk9WM0hvyE",
  "M12:Academic Listening": "jbO3AoxcA14",

  "M13:Matching Headings": "DWmo6nbhP0M",
  "M13:True/False/Not Given": "WYl9PX7Ua_Q",
  "M13:Yes/No/Not Given": "Rg0TcFqkvhE",
  "M13:Matching Information": "qfE07tfENSg",
  "M13:Sentence Completion": "X-YAG8FmFIg",
  "M13:Diagram Labelling": "f9FxdzQfH-I",
  "M13:Reading Academic Texts": "m9x9fZCBIMY",

  "M14:Introduction to Task 1": "scxTbnfLWaE",
  "M14:Charts and Graphs": "MWt5zIZddXQ",
  "M14:Tables": "MJNfnUJUwQE",
  "M14:Pie Charts": "71AlGeMbRfY",
  "M14:Line Graphs": "MtrBQSLDOrU",
  "M14:Bar Charts": "O5eb1uWsLrU",
  "M14:Process Diagrams": "cJdqncsYZVI",
  "M14:Maps": "tnQiluhQmTQ",
  "M14:Comparing Data": "eVq3enqcox8",
  "M14:Task 1 Vocabulary": "k8eg64zFino",

  "M15:Essay Structure": "ljF6Yu59K_g",
  "M15:Opinion Essays": "G9aEKgQp6fs",
  "M15:Discussion Essays": "SA6Q7XbiMf8",
  "M15:Problem-Solution Essays": "eXrWcodp94E",
  "M15:Advantages & Disadvantages Essays": "5k-EH8IcVzM",
  "M15:Two-Part Questions": "cF2g9jq9ZkY",
  "M15:Linking Words": "wSbv5bCY4No",
  "M15:Cohesion & Coherence": "TiY6Sp3dWSk",

  "M16:Speaking Part 1": "FjgeI68Iry8",
  "M16:Speaking Part 2 Cue Cards": "m5LbmcpnHcg",
  "M16:Speaking Part 3 Discussions": "-yN3zoJ5LYw",
  "M16:Expanding Answers": "VaKi09b19HY",
  "M16:Pronunciation Skills": "t9PRLpkCUSM",
  "M16:Fluency Development": "8pnGARTYMpg",
  "M16:Vocabulary for Speaking": "QPdPWAeLMoU",

  "M17:Understanding Accents": "uFh_xt93M_E",
  "M17:Predicting Answers": "nRRDXrLVM2s",
  "M17:Identifying Opinions": "HKoJnmyOwTs",
  "M17:Following Lectures": "YlZ1D52kNNQ",
  "M17:High-Band Listening Strategies": "9-aME_V_NGs",
  "M17:Advanced Listening Review": "VUtUOTrJ2Kk",

  "M18:Critical Reading": "sL88YhbIqMU",
  "M18:Speed Reading Techniques": "i_3kv_TdVxk",
  "M18:Inference Questions": "ICjIiaJHqHw",
  "M18:Writer\u2019s Opinion Questions": "hgvdWYSWMRM",
  "M18:Complex Academic Passages": "XDjYyFMbQcI",
  "M18:Reading Time Management": "ZMVkP5ZD-6U",

  "M19:Band 7+ Essay Structure": "ZiU4I1bXgNw",
  "M19:Advanced Vocabulary": "izMPYvuoaf0",
  "M19:Academic Writing Style": "BwQowyBUOYA",
  "M19:Complex Sentences": "8EA_dDD3hjQ",
  "M19:Data Analysis for Task 1": "esVd0749hts",
  "M19:High-Band Sample Essays": "D1dXH-vOSIA",
  "M19:Common Writing Mistakes": "Bxg8gqJz7wY",
  "M19:Task Achievement Strategies": "iOoZxpX0Zas",

  "M20:Speaking Like a Native": "SgNrKGl9rE8",
  "M20:Advanced Topic Discussions": "j6nGSqkCf9k",
  "M20:Abstract Ideas": "HOC9S_-Gbz0",
  "M20:Debate and Argument Skills": "-VVFwNo_29I",
  "M20:Idioms and Collocations": "7PEu8vVQl4o",
  "M20:Pronunciation for Band 8+": "DyFJiDZ8pUU",
  "M20:Speaking Confidence Building": "PC1UA04O-TQ",

  "M21:IELTS Exam Strategies": "polUc1sfod8",
  "M21:Time Management": "oSl-Av7jpLA",
  "M21:Mock Tests": "k_ucGw9cXDI",
  "M21:Error Analysis": "nIiZCov_fDI",
  "M21:Band Score Improvement": "baIkTadn2oA",
  "M21:Exam Day Preparation & Computer-Based IELTS": "59uM7GAYhk8",
  "M21:Academic vs General IELTS": "HcmEQLV38ac"
};
