/* TIH TOEFL Mastery — one distinct video per topic.
   Keys are module-qualified (M<n>:<topic title>) so a repeated title still
   gets its own clip. Loaded on demand by tih-video-runtime.js. */
window.TIH_TOPIC_VIDEOS = window.TIH_TOPIC_VIDEOS || {};
window.TIH_TOPIC_VIDEOS["toefl"] = {

  "M1:What is TOEFL?": "BhrmGH-Zsjw",
  "M1:TOEFL Test Structure": "6KamS4u3pYI",
  "M1:Scoring System": "fGrxgRAISlM",
  "M1:Welcome to the Course": "yITGJOxzf6c",
  "M1:How to Study Effectively": "Uf_DUtzHFsU",
  "M1:Study Plan": "yIUay9T42bM",
  "M1:Test Registration": "tHgeWQMyQS4",

  "M2:Parts of Speech": "kP_VkuB08qY",
  "M2:Nouns": "JhnGD0w_gPY",
  "M2:Pronouns": "uygUQYu0D0g",
  "M2:Verbs": "t6eQAQE1F10",
  "M2:Verb Tenses": "HWjRVkTNoNM",
  "M2:Subject-Verb Agreement": "4NkXM1j3seA",
  "M2:Adjectives": "zOgtZrn_4nU",
  "M2:Adverbs": "juHHpu1OGRI",
  "M2:Prepositions": "92XBCRYZ1S8",
  "M2:Conjunctions": "xo7iVZHqJeY",
  "M2:Articles": "UD8UV4rbH_I",
  "M2:Active & Passive Voice": "8x4K9INW2Zg",
  "M2:Direct & Indirect Speech": "LVB4O0BSZBQ",
  "M2:Conditional Sentences": "mJS9Dh5hPNg",
  "M2:Relative Clauses": "9FJ36GjiLvQ",
  "M2:Modals": "36wG9pSYu7Q",
  "M2:Gerunds & Infinitives": "1VaoDZpzWTw",
  "M2:Punctuation": "pE_WqqUeMo8",
  "M2:Common Grammar Mistakes": "Qp_wd37HL2g",

  "M3:Academic Vocabulary": "usdteThDjYI",
  "M3:Word Formation": "sNMdx0yTPgw",
  "M3:Prefixes & Suffixes": "0diRbQ-mgfo",
  "M3:Synonyms": "9X06MQrqusE",
  "M3:Antonyms": "qOjBoRLV368",
  "M3:Collocations": "Uxk9CbwW-7Y",
  "M3:Idioms": "6DbCTfepYgM",
  "M3:Phrasal Verbs": "r7VKVXbaj_Y",
  "M3:Context Clues": "CiNggzdWkIo",
  "M3:Vocabulary Review": "fE0W18Yz9hM",

  "M4:Reading Strategies": "InH3JtIJ7Tg",
  "M4:Skimming": "SRHNKzXxu6o",
  "M4:Scanning": "RtcXr0_201A",
  "M4:Main Ideas": "eVLZ8N3QQ9g",
  "M4:Supporting Details": "eGfMOcrxu9I",
  "M4:Vocabulary Questions": "iMn9Cs87DIg",
  "M4:Inference Questions": "b2Xsn4K_JG4",
  "M4:Reference Questions": "hssDB_50iZo",
  "M4:Sentence Simplification": "zSOmCGC3Cjc",
  "M4:Summary Questions": "W0NFBxRxnXQ",
  "M4:Reading Speed": "nOp9KAXgOOU",
  "M4:Timed Reading Practice": "D4op4qp9MB0",

  "M5:Listening Strategies": "WK6cG39EzT0",
  "M5:Note-Taking": "SDvuSHVkWUA",
  "M5:Campus Conversations": "R0-F2QHVPFw",
  "M5:Academic Lectures": "ldR8plSGMmU",
  "M5:Main Idea Questions": "IlsCIsdocdE",
  "M5:Detail Questions": "ZHKXOzmq6F0",
  "M5:Purpose Questions": "XwrQ12HZzuY",
  "M5:Inference Questions": "GZ6u0qAnAJk",
  "M5:Attitude Questions": "i_3BtrDYeSo",

  "M6:TOEFL Speaking Overview": "MQU6w-pINAM",
  "M6:Independent Speaking": "LQ-YY3sUE3k",
  "M6:Integrated Speaking": "kkQRIDDPe7Q",
  "M6:Organizing Responses": "W5lpcpoFc2Q",
  "M6:Speaking Templates": "YvpWvDk9H-U",
  "M6:Pronunciation": "ESBx-NBXK0c",
  "M6:Fluency": "-JVU2dgB4wo",
  "M6:Speaking Practice": "qKspcmSn9hw",

  "M7:Writing Overview": "h0N9hBQW43I",
  "M7:Integrated Writing": "njL86TkjK6E",
  "M7:Academic Discussion Writing": "WqCcgHe2BVM",
  "M7:Essay Structure": "nUq2SG3ZuyQ",
  "M7:Thesis Statements": "DFp1uGTXo4Q",
  "M7:Supporting Ideas": "B-Jifl1Mvmk",
  "M7:Transitions": "CpDTxvxuFpM",
  "M7:Editing": "nkAT7uUKQ2U",
  "M7:Model Essays": "WDNXsHUnyHk",

  "M8:English Sounds": "Ft17a7tyjMM",
  "M8:Stress": "5qv0mh4LoM4",
  "M8:Intonation": "cehPekFT_5I",
  "M8:Connected Speech": "Nbp--6rPq0Q",
  "M8:Public Speaking Practice": "-nIqG1KDzE4",

  "M9:Guessing Strategies": "RPxMMMU2oN8",
  "M9:Time Management": "YAKgDHWiQ-4",
  "M9:Common Mistakes": "2lz0pDG196M",
  "M9:Exam-Day Tips": "1E6QP3u85MU",
  "M9:Stress Management": "2WQ8_EDKeaU"
};
